# Generated by Django 4.2.2 on 2023-12-14 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='ref_no',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Reference Number'),
        ),
    ]
